server:
  port: 7003

# eureka配置
  # Eureka配置：配置服务注册中心地址
eureka:
  instance:
    hostname: eureka7003.com #修改Eureka上的默认描述信息
  client:
    refister-with-eureka: false  #是否注册自己
    fetch-registry: false  #false为自己为注册中心
    service-url:
      #  单机模式：  http://${eureka.instance.hostname}:${server.port}
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

