server:
  port: 81
#eureka 配置
eureka:
  client:
#    8.22 不能使用feign加
    fetch-registry: true
    register-with-eureka: false   #不向eureka注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
