server:
  port: 9527
spring:
  application:
    name: springcloud-zuul

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true #改为true后默认显示的是ip地址而不再是localhost  方便团队不同人使用

# info配置
info:
  # 项目的名称
  app.name: cvzhanshi-springcloud
  # 公司的名称
  company.name: blog.cvzhanshi.com

#  访问的地址  http://www.qiu.kai.xin.com:9527/springcloud-provider-dept/dept/get/1

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept   #固定的填项目名称
#    http://www.qiu.kai.xin.com:9527/mydept/dept/get/1
    mydept.path: /mydept/**   #该项目访问的前缀
#  ignored-services: springcloud-provider-dept    #阻止使用项目名称访问
  ignored-services: "*"   #阻止使用项目名称访问
  # 设置公共的前缀
#  http://www.qiu.kai.xin.com:9527/qiu/mydept/dept/get/1
  prefix: /qiu