

server:
  port: 9527

spring:
  application:
    name: cloud-gateway
#    配置路由
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心动态查u你更加爱你路由的功能,利用微服务名进行路由
      routes:
        - id: payment_routh #payment_router   #路由id，没有固定规则但要求位移，建议配合服务名
#          uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service     #匹配后提供服务的路由地址   实现的是动态连接
          predicates:
            - Path=/payment/get/**    #断言 ，路径相匹配的进行路由

        - id: payment_routh2 #payment_router   #路由id，没有固定规则但要求位移，建议配合服务名
#          uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service         #匹配后提供服务的路由地址    实现的是动态连接
          predicates:
            - Path=/payment/lb/**    #断言 ，路径相匹配的进行路由
            - After=2021-08-28T22:08:48.907+08:00[Asia/Shanghai]  #要在这个时间后这个请求才可以生效
#            curl 控制台访问  baba@Air-von-baba ~ % curl http://localhost:9527/payment/lb --cookie "username=zzyy"
#            - Cookie=username,zzyy  #携带参数时需要添加cooike
#            - Header=X-Request-Id, \d+   #请求头要带有X-Request-Id属性并且为整数的正则表达式


eureka:
  instance:
    hostname: cloud-gateway

  client:
    #    表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #    集群需要配置问true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/    #,http://eureka7002.com:7002/eureka/