server:
  port: 83

spring:
  application:
    name: nacos-order-consumer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848



# 消费者微服务的名称
service-url:
#  nacos-payment-provider
  nacos-user-service: http://nacos-payment-provider