server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: qiu/kai/xin/pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring的配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    url: jdbc:mysql://localhost:3306/DB01?useUnicode=true&amp&characterEncoding=utf-8&amp&useSSL=false
    username: root
    password: hehe4396
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #controller 的接口：  http://springcloud-provider-dept-8001
    # springname springcloud-provider-dept-8001
    # 容器名称：spring-cloud-provider-dept-8001

# eureka的配置， 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance:
#    instance-id: spring-cloud-provider-dept-8001
info:
  app.name: qiukaixin
  company.name: qiu.qiu.qiu


#监控中心