server:
  port: 8008

spring:
  application:
    name: cloud-provider-hystrix-payment

# eureka的配置， 服务注册到哪里
eureka:
  client:
    #    表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #    集群需要配置问true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/    #,http://eureka7002.com:7002/eureka/
#  #      用来区分服务的名称
#  instance:
#    instance-id: payment8001
#    #    配置这个可以在鼠标停留的时候查看ip地址
#    prefer-ip-address: true
#    #    eureka客户端在收到最后一次心跳等待时间上限，单位为（默认为90秒,超时将剔除服务
#    lease-expiration-duration-in-seconds: 1
#    #    eureka客户端向服务器发送心跳的时间间隔，单位为秒(默认是30秒)
#    lease-renewal-interval-in-seconds: 1