server:
  port: 8001

spring:
  application:
#    这个是可以作为集群的名字的
#    会作为注册中心的名称
    name: cloud-payment-service
    #    ********************
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #      采样率介于0和1之间，1表示全部采集
      probability: 1
      #    ********************
  datasource:
#
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&amp&characterEncoding=utf-8&amp&useSSL=false
    username: root
    password: hehe4396
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# eureka的配置， 服务注册到哪里
eureka:
  client:
#    表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
#    集群需要配置问true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  #      用来区分服务的名称
  instance:
    instance-id: payment8001
    #    配置这个可以在鼠标停留的时候查看ip地址
    prefer-ip-address: true
    #    eureka客户端在收到最后一次心跳等待时间上限，单位为（默认为90秒,超时将剔除服务
    lease-expiration-duration-in-seconds: 1
    #    eureka客户端向服务器发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: qiu.kai.xin.entities  #别名