server:
  port: 8002

spring:
  application:
#    这个是可以作为集群的名字的
#    会作为注册中心的名称
    name: cloud-payment-service
  datasource:
#
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&amp&characterEncoding=utf-8&amp&useSSL=false
    username: root
    password: hehe4396
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# eureka的配置， 服务注册到哪里
eureka:
  client:
#    表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
#    集群需要配置问true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#      用来区分服务的名称
  instance:
    instance-id: payment8002
    #    配置这个可以在鼠标停留的时候查看ip地址
    prefer-ip-address: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: qiu.kai.xin.entities  #别名