server:
  port: 7002

# eureka的配置， 服务注册到哪里
eureka:
  instance:
    hostname: eureka7002.com   #eureka服务端的实例名称
  #    instance-id: localhost
  client:
#        refister-with-eureka: false  #是否注册自己
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

      #    false表示自己端就是注册中心，我的职责即使维护服务器实例，并不需要检索服务
    #      地址解析有问题
    # prefer-ip-address: true      #地址解析有问题
#    false表示不向注册中心注册自己


#  instance:
#    instance-id: spring-cloud-provider-dept-8005